# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'WQToolKitDemo' do

  pod 'WQAlert', '~> 0.0.2'
  target 'WQToolKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WQToolKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
